### 상품 등록 ( 셀러 )
POST https://localhost:8080/seller/product
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "description": "테스트 상품입니다.",
  "name": "테스트 상품",
  "items": [
    {
      "count": 2,
      "name": "테스트 상품 아이템",
      "price": 10000
    }
  ]
}

### 상품 아이템 등록 ( 셀러 )
POST https://localhost:8080/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "productId": 1,
  "count": 2,
  "name": "테스트 상품 아이템",
  "price": 10000
}

### 상품 수정 ( 셀러 )
PUT https://localhost:8080/seller/product
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "description": "테스트 상품입니다.",
  "name": "테스트 상품 수정",
  "id": 1,
  "items": [
    {
      "id": 1,
      "count": 2,
      "name": "테스트 상품 아이템 수정",
      "price": 10000
    }
  ]
}

### 상품 아이템 수정 ( 셀러 )
PUT https://localhost:8080/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "id": 1,
  "productId": 1,
  "count": 2,
  "name": "테스트 상품 아이템",
  "price": 10000
}

### 상품 삭제 ( 셀러 )
DELETE https://localhost:8080/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: ${token}


### 상품 아이템 삭제 ( 셀러 )
DELETE https://localhost:8080/seller/product/item?id=1
Content-Type: application/json
X-AUTH-TOKEN: ${token}

### 상품 검색
GET https://localhost:8080/search/product?name=테스트 상품
Content-Type: application/json


### 상품 디테일 검색 ( 셀러 )
GET https://localhost:8080/search/product/detail?productId=1
Content-Type: application/json


### 카트 추가
### 상품 등록 ( 셀러 )
POST https://localhost:8080/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "description": "테스트 상품입니다.",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "테스트 상품 아이템",
      "price": 10000
    }
  ],
  "name": "테스트 상품",
  "sellerId": 1
}

