### 상품 등록 ( 셀러 )
POST https://localhost:8080/seller/product
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "description": "테스트 상품입니다.",
  "name": "테스트 상품",
  "items": [
    {
      "count": 2,
      "name": "테스트 상품 아이템",
      "price": 10000
    }
  ]
}

### 상품 아이템 등록 ( 셀러 )
POST https://localhost:8080/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "productId": 1,
  "count": 2,
  "name": "테스트 상품 아이템",
  "price": 10000
}

### 상품 수정 ( 셀러 )
PUT https://localhost:8080/seller/product
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "description": "테스트 상품입니다.",
  "name": "테스트 상품 수정",
  "id": 1,
  "items": [
    {
      "id": 1,
      "count": 2,
      "name": "테스트 상품 아이템 수정",
      "price": 10000
    }
  ]
}

### 상품 아이템 수정 ( 셀러 )
PUT https://localhost:8080/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "id": 1,
  "productId": 1,
  "count": 2,
  "name": "테스트 상품 아이템",
  "price": 10000
}

### 상품 삭제 ( 셀러 )
DELETE https://localhost:8080/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: ${token}


### 상품 아이템 삭제 ( 셀러 )
DELETE https://localhost:8080/seller/product/item?id=1
Content-Type: application/json
X-AUTH-TOKEN: ${token}




