### 회원 가입( 고객 )
POST https://localhost:8080/signup/customer
Content-Type: application/json

{
  "birth": "2000-01-01",
  "email": "test@test.com",
  "name": "홍길동",
  "password": "1234",
  "phone": "010-1234-5678"
}

### 이메일 인증 ( 고객 )
GET https://localhost:8080/signup/customer/verify?email=${email}&code=${code}

### 로그인 ( 고객 )
POST https://localhost:8080/signin/customer
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### 회원 정보 조회 ( 고객 )
GET https://localhost:8080/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: ${token}

### 잔액 변경 ( 고객 )
POST https://localhost:8080/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: ${token}

{
  "from": "server",
  "message": "돈 충전",
  "money": 10000
}

### 회원 가입 ( 셀러 )
POST https://localhost:8080/signup/seller
Content-Type: application/json

{
  "birth": "2000-01-01",
  "email": "test@test.com",
  "name": "홍길동",
  "password": "1234",
  "phone": "010-1234-5678"
}

### 이메일 인증 ( 셀러 )
GET https://localhost:8080/signup/seller/verify?email=${email}&code=${code}

### 로그인 ( 셀러 )
POST https://localhost:8080/signin/seller
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}


