server:
  port: ${PORT.NO:8080}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://${YOUR_HOST:localhost}:3306/${YOUR_DB_NAME:zeroorder}?useSSL=false&userUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${YOUR_ID:root}
    password: ${YOUR_PASSWORD:7845120qwe}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
feign:
  okhttp:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true
